name: Mypy

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyTorch dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch and related packages first
        pip install torch==2.0.0 --index-url https://download.pytorch.org/whl/cpu
        pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
        pip install torch-sparse -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
        pip install torch-geometric
    - name: Install dependencies
      run: |
        pip install mypy
        pip install -e ".[dev]"  # Install package with dev dependencies
    - name: Type checking with mypy
      run: |
        mypy src/ tests/ scripts/ 