# Runs pytest only

name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install numpy==1.24.0
      
      - name: Install PyTorch stack
        run: |
          pip install torch==2.0.0
          pip install torch-scatter==2.1.1 torch-sparse==0.6.17 -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
          pip install torch-geometric==2.3.0
      
      - name: Install package
        run: |
          pip install -e ".[test]"
      
      - name: Run pytest
        run: |
          pytest tests/ --cov -v
