# Runs pytest only

name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install PyTorch dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.0 --index-url https://download.pytorch.org/whl/cpu
          pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
          pip install torch-sparse -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
          pip install torch-geometric
      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install -e ".[test]"
      - name: Run pytest
        run: |
          pytest tests/ --cov -v
